// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wau_registry.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NatStatus NAT 穿透状态
type NatStatus int32

const (
	NatStatus_NAT_STATUS_UNSPECIFIED NatStatus = 0
	NatStatus_NAT_STATUS_PUBLIC      NatStatus = 1 // 公网可达
	NatStatus_NAT_STATUS_PRIVATE     NatStatus = 2 // 在 NAT 后
	NatStatus_NAT_STATUS_RELAY       NatStatus = 3 // 走中继
)

// Enum value maps for NatStatus.
var (
	NatStatus_name = map[int32]string{
		0: "NAT_STATUS_UNSPECIFIED",
		1: "NAT_STATUS_PUBLIC",
		2: "NAT_STATUS_PRIVATE",
		3: "NAT_STATUS_RELAY",
	}
	NatStatus_value = map[string]int32{
		"NAT_STATUS_UNSPECIFIED": 0,
		"NAT_STATUS_PUBLIC":      1,
		"NAT_STATUS_PRIVATE":     2,
		"NAT_STATUS_RELAY":       3,
	}
)

func (x NatStatus) Enum() *NatStatus {
	p := new(NatStatus)
	*p = x
	return p
}

func (x NatStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NatStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wau_registry_proto_enumTypes[0].Descriptor()
}

func (NatStatus) Type() protoreflect.EnumType {
	return &file_wau_registry_proto_enumTypes[0]
}

func (x NatStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NatStatus.Descriptor instead.
func (NatStatus) EnumDescriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{0}
}

// NodeType 节点类型
type NodeType int32

const (
	NodeType_NODE_TYPE_UNSPECIFIED NodeType = 0
	NodeType_NODE_TYPE_KERNEL      NodeType = 1 // WAU Kernel
	NodeType_NODE_TYPE_AGENT       NodeType = 2 // AI Agent
	NodeType_NODE_TYPE_GATEWAY     NodeType = 3 // A2A Gateway
	NodeType_NODE_TYPE_CLI         NodeType = 4 // wau-cli
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNSPECIFIED",
		1: "NODE_TYPE_KERNEL",
		2: "NODE_TYPE_AGENT",
		3: "NODE_TYPE_GATEWAY",
		4: "NODE_TYPE_CLI",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED": 0,
		"NODE_TYPE_KERNEL":      1,
		"NODE_TYPE_AGENT":       2,
		"NODE_TYPE_GATEWAY":     3,
		"NODE_TYPE_CLI":         4,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_wau_registry_proto_enumTypes[1].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_wau_registry_proto_enumTypes[1]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{1}
}

type WatchPeersResponse_EventType int32

const (
	WatchPeersResponse_EVENT_TYPE_UNSPECIFIED  WatchPeersResponse_EventType = 0
	WatchPeersResponse_EVENT_TYPE_REGISTERED   WatchPeersResponse_EventType = 1
	WatchPeersResponse_EVENT_TYPE_DEREGISTERED WatchPeersResponse_EventType = 2
	WatchPeersResponse_EVENT_TYPE_UPDATED      WatchPeersResponse_EventType = 3
)

// Enum value maps for WatchPeersResponse_EventType.
var (
	WatchPeersResponse_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_REGISTERED",
		2: "EVENT_TYPE_DEREGISTERED",
		3: "EVENT_TYPE_UPDATED",
	}
	WatchPeersResponse_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":  0,
		"EVENT_TYPE_REGISTERED":   1,
		"EVENT_TYPE_DEREGISTERED": 2,
		"EVENT_TYPE_UPDATED":      3,
	}
)

func (x WatchPeersResponse_EventType) Enum() *WatchPeersResponse_EventType {
	p := new(WatchPeersResponse_EventType)
	*p = x
	return p
}

func (x WatchPeersResponse_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchPeersResponse_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_wau_registry_proto_enumTypes[2].Descriptor()
}

func (WatchPeersResponse_EventType) Type() protoreflect.EnumType {
	return &file_wau_registry_proto_enumTypes[2]
}

func (x WatchPeersResponse_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchPeersResponse_EventType.Descriptor instead.
func (WatchPeersResponse_EventType) EnumDescriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{12, 0}
}

// PeerInfo 网络层节点信息（libp2p）
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PeerId        string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"` // libp2p PeerID
	Addrs         []string               `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`                 // libp2p multiaddrs
	NodeType      NodeType               `protobuf:"varint,4,opt,name=node_type,json=nodeType,proto3,enum=wau.registry.v1.NodeType" json:"node_type,omitempty"`
	NatStatus     NatStatus              `protobuf:"varint,5,opt,name=nat_status,json=natStatus,proto3,enum=wau.registry.v1.NatStatus" json:"nat_status,omitempty"`
	Protocols     []string               `protobuf:"bytes,6,rep,name=protocols,proto3" json:"protocols,omitempty"` // ["a2a/1.0", "libp2p"]
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_wau_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PeerInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *PeerInfo) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *PeerInfo) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *PeerInfo) GetNatStatus() NatStatus {
	if x != nil {
		return x.NatStatus
	}
	return NatStatus_NAT_STATUS_UNSPECIFIED
}

func (x *PeerInfo) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *PeerInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *PeerInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PeerFilter peer 过滤条件
type PeerFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeType      NodeType               `protobuf:"varint,1,opt,name=node_type,json=nodeType,proto3,enum=wau.registry.v1.NodeType" json:"node_type,omitempty"`
	Skill         string                 `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"`
	Universe      string                 `protobuf:"bytes,3,opt,name=universe,proto3" json:"universe,omitempty"`
	NamePattern   string                 `protobuf:"bytes,4,opt,name=name_pattern,json=namePattern,proto3" json:"name_pattern,omitempty"` // 模糊匹配
	OnlineOnly    bool                   `protobuf:"varint,5,opt,name=online_only,json=onlineOnly,proto3" json:"online_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerFilter) Reset() {
	*x = PeerFilter{}
	mi := &file_wau_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerFilter) ProtoMessage() {}

func (x *PeerFilter) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerFilter.ProtoReflect.Descriptor instead.
func (*PeerFilter) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{1}
}

func (x *PeerFilter) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *PeerFilter) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *PeerFilter) GetUniverse() string {
	if x != nil {
		return x.Universe
	}
	return ""
}

func (x *PeerFilter) GetNamePattern() string {
	if x != nil {
		return x.NamePattern
	}
	return ""
}

func (x *PeerFilter) GetOnlineOnly() bool {
	if x != nil {
		return x.OnlineOnly
	}
	return false
}

// AgentCard 注册中心版（与 kernel 共享定义，但独立命名以允许独立演进）
// 注：这里重复定义是为了注册中心的独立部署，结构上与 kernel 的 AgentCard 保持一致
type RegistryAgentCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Skills        []string               `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`
	Universes     []string               `protobuf:"bytes,5,rep,name=universes,proto3" json:"universes,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryAgentCard) Reset() {
	*x = RegistryAgentCard{}
	mi := &file_wau_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryAgentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryAgentCard) ProtoMessage() {}

func (x *RegistryAgentCard) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryAgentCard.ProtoReflect.Descriptor instead.
func (*RegistryAgentCard) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegistryAgentCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryAgentCard) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegistryAgentCard) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegistryAgentCard) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *RegistryAgentCard) GetUniverses() []string {
	if x != nil {
		return x.Universes
	}
	return nil
}

func (x *RegistryAgentCard) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegistryAgentCard) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type RegisterPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *PeerInfo              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerRequest) Reset() {
	*x = RegisterPeerRequest{}
	mi := &file_wau_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerRequest) ProtoMessage() {}

func (x *RegisterPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerRequest.ProtoReflect.Descriptor instead.
func (*RegisterPeerRequest) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterPeerRequest) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

type RegisterPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPeerResponse) Reset() {
	*x = RegisterPeerResponse{}
	mi := &file_wau_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPeerResponse) ProtoMessage() {}

func (x *RegisterPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPeerResponse.ProtoReflect.Descriptor instead.
func (*RegisterPeerResponse) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterPeerResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterPeerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeregisterPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterPeerRequest) Reset() {
	*x = DeregisterPeerRequest{}
	mi := &file_wau_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterPeerRequest) ProtoMessage() {}

func (x *DeregisterPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterPeerRequest.ProtoReflect.Descriptor instead.
func (*DeregisterPeerRequest) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{5}
}

func (x *DeregisterPeerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeregisterPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterPeerResponse) Reset() {
	*x = DeregisterPeerResponse{}
	mi := &file_wau_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterPeerResponse) ProtoMessage() {}

func (x *DeregisterPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterPeerResponse.ProtoReflect.Descriptor instead.
func (*DeregisterPeerResponse) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{6}
}

type GetPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerRequest) Reset() {
	*x = GetPeerRequest{}
	mi := &file_wau_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerRequest) ProtoMessage() {}

func (x *GetPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerRequest.ProtoReflect.Descriptor instead.
func (*GetPeerRequest) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{7}
}

func (x *GetPeerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *PeerInfo              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerResponse) Reset() {
	*x = GetPeerResponse{}
	mi := &file_wau_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerResponse) ProtoMessage() {}

func (x *GetPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerResponse.ProtoReflect.Descriptor instead.
func (*GetPeerResponse) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{8}
}

func (x *GetPeerResponse) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *GetPeerResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *PeerFilter            `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersRequest) Reset() {
	*x = GetPeersRequest{}
	mi := &file_wau_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersRequest) ProtoMessage() {}

func (x *GetPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersRequest.ProtoReflect.Descriptor instead.
func (*GetPeersRequest) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{9}
}

func (x *GetPeersRequest) GetFilter() *PeerFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type GetPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	mi := &file_wau_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{10}
}

func (x *GetPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *GetPeersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WatchPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *PeerFilter            `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPeersRequest) Reset() {
	*x = WatchPeersRequest{}
	mi := &file_wau_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPeersRequest) ProtoMessage() {}

func (x *WatchPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPeersRequest.ProtoReflect.Descriptor instead.
func (*WatchPeersRequest) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{11}
}

func (x *WatchPeersRequest) GetFilter() *PeerFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type WatchPeersResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Event         WatchPeersResponse_EventType `protobuf:"varint,1,opt,name=event,proto3,enum=wau.registry.v1.WatchPeersResponse_EventType" json:"event,omitempty"`
	Peer          *PeerInfo                    `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPeersResponse) Reset() {
	*x = WatchPeersResponse{}
	mi := &file_wau_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPeersResponse) ProtoMessage() {}

func (x *WatchPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPeersResponse.ProtoReflect.Descriptor instead.
func (*WatchPeersResponse) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{12}
}

func (x *WatchPeersResponse) GetEvent() WatchPeersResponse_EventType {
	if x != nil {
		return x.Event
	}
	return WatchPeersResponse_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchPeersResponse) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

type RegisterCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *RegistryAgentCard     `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCardRequest) Reset() {
	*x = RegisterCardRequest{}
	mi := &file_wau_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCardRequest) ProtoMessage() {}

func (x *RegisterCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCardRequest.ProtoReflect.Descriptor instead.
func (*RegisterCardRequest) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterCardRequest) GetCard() *RegistryAgentCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type RegisterCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterCardResponse) Reset() {
	*x = RegisterCardResponse{}
	mi := &file_wau_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCardResponse) ProtoMessage() {}

func (x *RegisterCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCardResponse.ProtoReflect.Descriptor instead.
func (*RegisterCardResponse) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{14}
}

type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_wau_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{15}
}

func (x *GetCardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *RegistryAgentCard     `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_wau_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{16}
}

func (x *GetCardResponse) GetCard() *RegistryAgentCard {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *GetCardResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         string                 `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	Universe      string                 `protobuf:"bytes,2,opt,name=universe,proto3" json:"universe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsRequest) Reset() {
	*x = GetCardsRequest{}
	mi := &file_wau_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsRequest) ProtoMessage() {}

func (x *GetCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsRequest.ProtoReflect.Descriptor instead.
func (*GetCardsRequest) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{17}
}

func (x *GetCardsRequest) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

func (x *GetCardsRequest) GetUniverse() string {
	if x != nil {
		return x.Universe
	}
	return ""
}

type GetCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*RegistryAgentCard   `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsResponse) Reset() {
	*x = GetCardsResponse{}
	mi := &file_wau_registry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsResponse) ProtoMessage() {}

func (x *GetCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsResponse.ProtoReflect.Descriptor instead.
func (*GetCardsResponse) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{18}
}

func (x *GetCardsResponse) GetCards() []*RegistryAgentCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *GetCardsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_wau_registry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{19}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PeerCount     int64                  `protobuf:"varint,2,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	CardCount     int64                  `protobuf:"varint,3,opt,name=card_count,json=cardCount,proto3" json:"card_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_wau_registry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wau_registry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_wau_registry_proto_rawDescGZIP(), []int{20}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetPeerCount() int64 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *PingResponse) GetCardCount() int64 {
	if x != nil {
		return x.CardCount
	}
	return 0
}

var File_wau_registry_proto protoreflect.FileDescriptor

const file_wau_registry_proto_rawDesc = "" +
	"\n" +
	"\x12wau_registry.proto\x12\x0fwau.registry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x03\n" +
	"\bPeerInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x14\n" +
	"\x05addrs\x18\x03 \x03(\tR\x05addrs\x126\n" +
	"\tnode_type\x18\x04 \x01(\x0e2\x19.wau.registry.v1.NodeTypeR\bnodeType\x129\n" +
	"\n" +
	"nat_status\x18\x05 \x01(\x0e2\x1a.wau.registry.v1.NatStatusR\tnatStatus\x12\x1c\n" +
	"\tprotocols\x18\x06 \x03(\tR\tprotocols\x127\n" +
	"\tlast_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12C\n" +
	"\bmetadata\x18\b \x03(\v2'.wau.registry.v1.PeerInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x01\n" +
	"\n" +
	"PeerFilter\x126\n" +
	"\tnode_type\x18\x01 \x01(\x0e2\x19.wau.registry.v1.NodeTypeR\bnodeType\x12\x14\n" +
	"\x05skill\x18\x02 \x01(\tR\x05skill\x12\x1a\n" +
	"\buniverse\x18\x03 \x01(\tR\buniverse\x12!\n" +
	"\fname_pattern\x18\x04 \x01(\tR\vnamePattern\x12\x1f\n" +
	"\vonline_only\x18\x05 \x01(\bR\n" +
	"onlineOnly\"\xe4\x01\n" +
	"\x11RegistryAgentCard\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06skills\x18\x04 \x03(\tR\x06skills\x12\x1c\n" +
	"\tuniverses\x18\x05 \x03(\tR\tuniverses\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x127\n" +
	"\tlast_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"D\n" +
	"\x13RegisterPeerRequest\x12-\n" +
	"\x04peer\x18\x01 \x01(\v2\x19.wau.registry.v1.PeerInfoR\x04peer\"L\n" +
	"\x14RegisterPeerResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x15DeregisterPeerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16DeregisterPeerResponse\"$\n" +
	"\x0eGetPeerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"V\n" +
	"\x0fGetPeerResponse\x12-\n" +
	"\x04peer\x18\x01 \x01(\v2\x19.wau.registry.v1.PeerInfoR\x04peer\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"F\n" +
	"\x0fGetPeersRequest\x123\n" +
	"\x06filter\x18\x01 \x01(\v2\x1b.wau.registry.v1.PeerFilterR\x06filter\"Y\n" +
	"\x10GetPeersResponse\x12/\n" +
	"\x05peers\x18\x01 \x03(\v2\x19.wau.registry.v1.PeerInfoR\x05peers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"H\n" +
	"\x11WatchPeersRequest\x123\n" +
	"\x06filter\x18\x01 \x01(\v2\x1b.wau.registry.v1.PeerFilterR\x06filter\"\x81\x02\n" +
	"\x12WatchPeersResponse\x12C\n" +
	"\x05event\x18\x01 \x01(\x0e2-.wau.registry.v1.WatchPeersResponse.EventTypeR\x05event\x12-\n" +
	"\x04peer\x18\x02 \x01(\v2\x19.wau.registry.v1.PeerInfoR\x04peer\"w\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_TYPE_REGISTERED\x10\x01\x12\x1b\n" +
	"\x17EVENT_TYPE_DEREGISTERED\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_UPDATED\x10\x03\"M\n" +
	"\x13RegisterCardRequest\x126\n" +
	"\x04card\x18\x01 \x01(\v2\".wau.registry.v1.RegistryAgentCardR\x04card\"\x16\n" +
	"\x14RegisterCardResponse\"$\n" +
	"\x0eGetCardRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"_\n" +
	"\x0fGetCardResponse\x126\n" +
	"\x04card\x18\x01 \x01(\v2\".wau.registry.v1.RegistryAgentCardR\x04card\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"C\n" +
	"\x0fGetCardsRequest\x12\x14\n" +
	"\x05skill\x18\x01 \x01(\tR\x05skill\x12\x1a\n" +
	"\buniverse\x18\x02 \x01(\tR\buniverse\"b\n" +
	"\x10GetCardsResponse\x128\n" +
	"\x05cards\x18\x01 \x03(\v2\".wau.registry.v1.RegistryAgentCardR\x05cards\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\r\n" +
	"\vPingRequest\"d\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x02 \x01(\x03R\tpeerCount\x12\x1d\n" +
	"\n" +
	"card_count\x18\x03 \x01(\x03R\tcardCount*l\n" +
	"\tNatStatus\x12\x1a\n" +
	"\x16NAT_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11NAT_STATUS_PUBLIC\x10\x01\x12\x16\n" +
	"\x12NAT_STATUS_PRIVATE\x10\x02\x12\x14\n" +
	"\x10NAT_STATUS_RELAY\x10\x03*z\n" +
	"\bNodeType\x12\x19\n" +
	"\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10NODE_TYPE_KERNEL\x10\x01\x12\x13\n" +
	"\x0fNODE_TYPE_AGENT\x10\x02\x12\x15\n" +
	"\x11NODE_TYPE_GATEWAY\x10\x03\x12\x11\n" +
	"\rNODE_TYPE_CLI\x10\x042\x8a\x06\n" +
	"\x0fRegistryService\x12[\n" +
	"\fRegisterPeer\x12$.wau.registry.v1.RegisterPeerRequest\x1a%.wau.registry.v1.RegisterPeerResponse\x12a\n" +
	"\x0eDeregisterPeer\x12&.wau.registry.v1.DeregisterPeerRequest\x1a'.wau.registry.v1.DeregisterPeerResponse\x12L\n" +
	"\aGetPeer\x12\x1f.wau.registry.v1.GetPeerRequest\x1a .wau.registry.v1.GetPeerResponse\x12O\n" +
	"\bGetPeers\x12 .wau.registry.v1.GetPeersRequest\x1a!.wau.registry.v1.GetPeersResponse\x12W\n" +
	"\n" +
	"WatchPeers\x12\".wau.registry.v1.WatchPeersRequest\x1a#.wau.registry.v1.WatchPeersResponse0\x01\x12[\n" +
	"\fRegisterCard\x12$.wau.registry.v1.RegisterCardRequest\x1a%.wau.registry.v1.RegisterCardResponse\x12L\n" +
	"\aGetCard\x12\x1f.wau.registry.v1.GetCardRequest\x1a .wau.registry.v1.GetCardResponse\x12O\n" +
	"\bGetCards\x12 .wau.registry.v1.GetCardsRequest\x1a!.wau.registry.v1.GetCardsResponse\x12C\n" +
	"\x04Ping\x12\x1c.wau.registry.v1.PingRequest\x1a\x1d.wau.registry.v1.PingResponseBJZHgithub.com/wau/wau-registry-service/proto/gen/wau/registry/v1;registryv1b\x06proto3"

var (
	file_wau_registry_proto_rawDescOnce sync.Once
	file_wau_registry_proto_rawDescData []byte
)

func file_wau_registry_proto_rawDescGZIP() []byte {
	file_wau_registry_proto_rawDescOnce.Do(func() {
		file_wau_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wau_registry_proto_rawDesc), len(file_wau_registry_proto_rawDesc)))
	})
	return file_wau_registry_proto_rawDescData
}

var file_wau_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_wau_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_wau_registry_proto_goTypes = []any{
	(NatStatus)(0),                    // 0: wau.registry.v1.NatStatus
	(NodeType)(0),                     // 1: wau.registry.v1.NodeType
	(WatchPeersResponse_EventType)(0), // 2: wau.registry.v1.WatchPeersResponse.EventType
	(*PeerInfo)(nil),                  // 3: wau.registry.v1.PeerInfo
	(*PeerFilter)(nil),                // 4: wau.registry.v1.PeerFilter
	(*RegistryAgentCard)(nil),         // 5: wau.registry.v1.RegistryAgentCard
	(*RegisterPeerRequest)(nil),       // 6: wau.registry.v1.RegisterPeerRequest
	(*RegisterPeerResponse)(nil),      // 7: wau.registry.v1.RegisterPeerResponse
	(*DeregisterPeerRequest)(nil),     // 8: wau.registry.v1.DeregisterPeerRequest
	(*DeregisterPeerResponse)(nil),    // 9: wau.registry.v1.DeregisterPeerResponse
	(*GetPeerRequest)(nil),            // 10: wau.registry.v1.GetPeerRequest
	(*GetPeerResponse)(nil),           // 11: wau.registry.v1.GetPeerResponse
	(*GetPeersRequest)(nil),           // 12: wau.registry.v1.GetPeersRequest
	(*GetPeersResponse)(nil),          // 13: wau.registry.v1.GetPeersResponse
	(*WatchPeersRequest)(nil),         // 14: wau.registry.v1.WatchPeersRequest
	(*WatchPeersResponse)(nil),        // 15: wau.registry.v1.WatchPeersResponse
	(*RegisterCardRequest)(nil),       // 16: wau.registry.v1.RegisterCardRequest
	(*RegisterCardResponse)(nil),      // 17: wau.registry.v1.RegisterCardResponse
	(*GetCardRequest)(nil),            // 18: wau.registry.v1.GetCardRequest
	(*GetCardResponse)(nil),           // 19: wau.registry.v1.GetCardResponse
	(*GetCardsRequest)(nil),           // 20: wau.registry.v1.GetCardsRequest
	(*GetCardsResponse)(nil),          // 21: wau.registry.v1.GetCardsResponse
	(*PingRequest)(nil),               // 22: wau.registry.v1.PingRequest
	(*PingResponse)(nil),              // 23: wau.registry.v1.PingResponse
	nil,                               // 24: wau.registry.v1.PeerInfo.MetadataEntry
	(*timestamppb.Timestamp)(nil),     // 25: google.protobuf.Timestamp
}
var file_wau_registry_proto_depIdxs = []int32{
	1,  // 0: wau.registry.v1.PeerInfo.node_type:type_name -> wau.registry.v1.NodeType
	0,  // 1: wau.registry.v1.PeerInfo.nat_status:type_name -> wau.registry.v1.NatStatus
	25, // 2: wau.registry.v1.PeerInfo.last_seen:type_name -> google.protobuf.Timestamp
	24, // 3: wau.registry.v1.PeerInfo.metadata:type_name -> wau.registry.v1.PeerInfo.MetadataEntry
	1,  // 4: wau.registry.v1.PeerFilter.node_type:type_name -> wau.registry.v1.NodeType
	25, // 5: wau.registry.v1.RegistryAgentCard.last_seen:type_name -> google.protobuf.Timestamp
	3,  // 6: wau.registry.v1.RegisterPeerRequest.peer:type_name -> wau.registry.v1.PeerInfo
	3,  // 7: wau.registry.v1.GetPeerResponse.peer:type_name -> wau.registry.v1.PeerInfo
	4,  // 8: wau.registry.v1.GetPeersRequest.filter:type_name -> wau.registry.v1.PeerFilter
	3,  // 9: wau.registry.v1.GetPeersResponse.peers:type_name -> wau.registry.v1.PeerInfo
	4,  // 10: wau.registry.v1.WatchPeersRequest.filter:type_name -> wau.registry.v1.PeerFilter
	2,  // 11: wau.registry.v1.WatchPeersResponse.event:type_name -> wau.registry.v1.WatchPeersResponse.EventType
	3,  // 12: wau.registry.v1.WatchPeersResponse.peer:type_name -> wau.registry.v1.PeerInfo
	5,  // 13: wau.registry.v1.RegisterCardRequest.card:type_name -> wau.registry.v1.RegistryAgentCard
	5,  // 14: wau.registry.v1.GetCardResponse.card:type_name -> wau.registry.v1.RegistryAgentCard
	5,  // 15: wau.registry.v1.GetCardsResponse.cards:type_name -> wau.registry.v1.RegistryAgentCard
	6,  // 16: wau.registry.v1.RegistryService.RegisterPeer:input_type -> wau.registry.v1.RegisterPeerRequest
	8,  // 17: wau.registry.v1.RegistryService.DeregisterPeer:input_type -> wau.registry.v1.DeregisterPeerRequest
	10, // 18: wau.registry.v1.RegistryService.GetPeer:input_type -> wau.registry.v1.GetPeerRequest
	12, // 19: wau.registry.v1.RegistryService.GetPeers:input_type -> wau.registry.v1.GetPeersRequest
	14, // 20: wau.registry.v1.RegistryService.WatchPeers:input_type -> wau.registry.v1.WatchPeersRequest
	16, // 21: wau.registry.v1.RegistryService.RegisterCard:input_type -> wau.registry.v1.RegisterCardRequest
	18, // 22: wau.registry.v1.RegistryService.GetCard:input_type -> wau.registry.v1.GetCardRequest
	20, // 23: wau.registry.v1.RegistryService.GetCards:input_type -> wau.registry.v1.GetCardsRequest
	22, // 24: wau.registry.v1.RegistryService.Ping:input_type -> wau.registry.v1.PingRequest
	7,  // 25: wau.registry.v1.RegistryService.RegisterPeer:output_type -> wau.registry.v1.RegisterPeerResponse
	9,  // 26: wau.registry.v1.RegistryService.DeregisterPeer:output_type -> wau.registry.v1.DeregisterPeerResponse
	11, // 27: wau.registry.v1.RegistryService.GetPeer:output_type -> wau.registry.v1.GetPeerResponse
	13, // 28: wau.registry.v1.RegistryService.GetPeers:output_type -> wau.registry.v1.GetPeersResponse
	15, // 29: wau.registry.v1.RegistryService.WatchPeers:output_type -> wau.registry.v1.WatchPeersResponse
	17, // 30: wau.registry.v1.RegistryService.RegisterCard:output_type -> wau.registry.v1.RegisterCardResponse
	19, // 31: wau.registry.v1.RegistryService.GetCard:output_type -> wau.registry.v1.GetCardResponse
	21, // 32: wau.registry.v1.RegistryService.GetCards:output_type -> wau.registry.v1.GetCardsResponse
	23, // 33: wau.registry.v1.RegistryService.Ping:output_type -> wau.registry.v1.PingResponse
	25, // [25:34] is the sub-list for method output_type
	16, // [16:25] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_wau_registry_proto_init() }
func file_wau_registry_proto_init() {
	if File_wau_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wau_registry_proto_rawDesc), len(file_wau_registry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wau_registry_proto_goTypes,
		DependencyIndexes: file_wau_registry_proto_depIdxs,
		EnumInfos:         file_wau_registry_proto_enumTypes,
		MessageInfos:      file_wau_registry_proto_msgTypes,
	}.Build()
	File_wau_registry_proto = out.File
	file_wau_registry_proto_goTypes = nil
	file_wau_registry_proto_depIdxs = nil
}
